CREATE TABLE [dbo].[STD_CRS]
(
[Std_ID] [int] NOT NULL,
[Course_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STD_CRS] ADD CONSTRAINT [PK_STD_CRS] PRIMARY KEY CLUSTERED ([Std_ID], [Course_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STD_CRS] ADD CONSTRAINT [FK_STD_CRS_Course] FOREIGN KEY ([Course_ID]) REFERENCES [dbo].[Course] ([Course_ID])
GO
ALTER TABLE [dbo].[STD_CRS] ADD CONSTRAINT [FK_STD_CRS_Student] FOREIGN KEY ([Std_ID]) REFERENCES [dbo].[Student] ([Std_ID])
GO
