CREATE TABLE [dbo].[STD_QUES_EXAM]
(
[QuestionID] [int] NOT NULL,
[Std_Answer] [varchar] (20) COLLATE Latin1_General_CI_AS NOT NULL,
[ExamID] [int] NULL,
[Std_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STD_QUES_EXAM] ADD CONSTRAINT [PK_STD_QUES_EXAM] PRIMARY KEY CLUSTERED ([QuestionID], [Std_Answer]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STD_QUES_EXAM] ADD CONSTRAINT [FK_STD_QUES_EXAM_Exam] FOREIGN KEY ([ExamID]) REFERENCES [dbo].[Exam] ([ExamID])
GO
ALTER TABLE [dbo].[STD_QUES_EXAM] ADD CONSTRAINT [FK_STD_QUES_EXAM_Questions] FOREIGN KEY ([QuestionID]) REFERENCES [dbo].[Questions] ([QuestionID])
GO
ALTER TABLE [dbo].[STD_QUES_EXAM] ADD CONSTRAINT [FK_STD_QUES_EXAM_Student] FOREIGN KEY ([Std_ID]) REFERENCES [dbo].[Student] ([Std_ID])
GO
