CREATE TABLE [dbo].[STD_INS]
(
[Std_ID] [int] NOT NULL,
[Ins_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STD_INS] ADD CONSTRAINT [PK_STD_INS] PRIMARY KEY CLUSTERED ([Std_ID], [Ins_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STD_INS] ADD CONSTRAINT [FK_STD_INS_Instructor] FOREIGN KEY ([Ins_ID]) REFERENCES [dbo].[Instructor] ([Ins_ID])
GO
ALTER TABLE [dbo].[STD_INS] ADD CONSTRAINT [FK_STD_INS_Student] FOREIGN KEY ([Std_ID]) REFERENCES [dbo].[Student] ([Std_ID])
GO
