CREATE TABLE [dbo].[QUES_TYPE]
(
[TypeID] [int] NOT NULL,
[TypeName] [char] (10) COLLATE Latin1_General_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[QUES_TYPE] ADD CONSTRAINT [PK_QUES_TYPE] PRIMARY KEY CLUSTERED ([TypeID]) ON [PRIMARY]
GO
