CREATE TABLE [dbo].[INS_CRS]
(
[Course_ID] [int] NOT NULL,
[Instructor_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INS_CRS] ADD CONSTRAINT [PK_INS_CRS] PRIMARY KEY CLUSTERED ([Course_ID], [Instructor_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INS_CRS] ADD CONSTRAINT [FK_INS_CRS_Course] FOREIGN KEY ([Course_ID]) REFERENCES [dbo].[Course] ([Course_ID])
GO
ALTER TABLE [dbo].[INS_CRS] ADD CONSTRAINT [FK_INS_CRS_Instructor] FOREIGN KEY ([Instructor_ID]) REFERENCES [dbo].[Instructor] ([Ins_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
